version: "3.9"

services:
  wordpress:
    depends_on: 
      - mysql
    ports:
      - "8011:80"
    build:
      context: .
      args: 
        - "CNBUILD="
    volumes:
      - "wordpress:/var/www/html"
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_HOST=mysql

  mysql:
    image: "mysql:8"
    ports:
      - "3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db:/var/lib/mysql"
    environment: 
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress

volumes:
  wordpress:
  db:
