version: "3.9"

services:
  wordpress:
    env_file:
      - "./.env"
    depends_on: 
      - mysql
    ports:
      - "8081:80"
    build:
      context: .
      args: 
        - "CNBUILD="
    volumes:
      - "wordpress:/var/www/html"

  mysql:
    image: "mysql:8"
    env_file:
      - "./.env"
    ports:
      - "3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db:/var/lib/mysql"

volumes:
  wordpress:
  db:
